### ISSUE TITLE
Add ToolTips

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#10]

**Comment by jwildfire** [comment]
Should be easy enough. We can do this in 2.1.0.

**Comment by samussiah** [comment]
Tooltips which display what exactly?

**Comment by jwildfire** [comment]
Lets start with something like the tooltips shown [here](http://graphics.rhoworld.com/tools/aeexplorer/example4/)

**Comment by samussiah** [comment]
Tooltips added to minor row expand/collapse controls, major/minor category text, rate text, rate marks, and rate difference marks.

**Comment by samussiah** [comment]
http://bl.ocks.org/samussiah/raw/f326c788286234ce0644c4e556d07163/

**Comment by jwildfire** [comment]
Looks great! 

Is it easy to show the group level rates when mousing over a difference diamond? For example,  "Placebo (10%) vs. Active (5%): 5%"? If so, lets update that annotation, and remove the svg text that shows up with the circles when mousing over a diamond.

**Comment by jwildfire** [comment]
Also, is this all rolled in to the same branch as the refactor/modularization? If so, let's go ahead and move these issues to the v3.0.0 milestone. If not, we can ask Britt to test the changes and release it as  v2.1.0 in the next week or so

**Comment by samussiah** [comment]
Yup, all on refactor.  I've **_almost_** got it modularized.  After running 'npm run build' I'm having to make two edits to the built file to get an instance up and running.  I'll finalize tomorrow morning with all updates.

**Comment by samussiah** [comment]
http://bl.ocks.org/samussiah/raw/90e524b9ef2fdf8214d491aaca4cd3b3/

**Comment by brittsikora** [comment]
QCd this and it looks good - closing and checking off for the pull request
