### ISSUE TITLE
Show # of Enrolled/Randomized Participants

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#11]
Not sure the best way to handle this, but it would be good to have the number of relevant study participants shown somewhere on the chart. Maybe add a footnote for "X of X participants shown in this view"

**Comment by jwildfire** [comment]
Can implement this like the "overall" column shown here - http://graphics.rhoworld.com/tools/aeexplorer/example4/

**Comment by jwildfire** [comment]
Might be a bit complicated, but will try it in v2.1.0

**Comment by samussiah** [comment]
Total column added contingent on settings.defaults.totalCol is set to 'Show'.

**Comment by samussiah** [comment]
http://bl.ocks.org/samussiah/raw/f326c788286234ce0644c4e556d07163/

**Comment by brittsikora** [comment]
Total is showing an n that makes sense, so I'd say this is a pass. Closing and passing in pull request.
