### ISSUE TITLE
Change color scheme so yellow is not included

### ISSUE THREAD

**Issue by emmorris** [RhoInc/aeexplorer#127]
Currently when you group by RACE in the new version the colors change and one of the groups shows up as yellow.  That is really difficult to see on the white background of the table, so we should change it to a different color scheme that is easier to read.

**Comment by emmorris** [comment]
Hardcoded list of colors here:  https://github.com/RhoInc/aeexplorer/blob/master/src/chart/colorScale.js

Update those to these: http://colorbrewer2.org/#type=qualitative&scheme=Paired&n=10

**Comment by jwildfire** [comment]
Paired isn't really appropriate here (since the data isn't paired). We're already using a [colorbrewer palette](http://colorbrewer2.org/#type=qualitative&scheme=Set3&n=9) here, so just going to delete the yellow and replace it with the next available color (which is gray).

**Comment by jwildfire** [comment]
Actually, we use gray for total ... so just deleting yellow.

**Comment by danedexF5** [comment]
Yellow is gone, confirmed.
