### ISSUE TITLE
Reinitialize color scale when changing group. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#132]
Currently the `colorScale.domain()` is not reset, so new colors are used when the group variable is changed. Instead, the original colors should be re-assigned to the new groups.

**Comment by jwildfire** [comment]
## Test Notes

Use [test page](https://rawgit.com/RhoInc/aeexplorer/v3.3.1-dev/test-page/index.html) or CAT to confirm that colors are re-used when changing the group variables. First group column should always be blue, 2nd green, 3rd orange, etc. Total column should always be gray.

**Comment by rchronowic** [comment]
Tested on Test Page in both Firefox and Chrome, colors are re-used when changing group variables, although order is 1. Blue, 2. Green, 3. Purple, 4. Orange and total remains gray.
