### ISSUE TITLE
Prevent charts with too many groups when the group variable changes

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#133]
Not sure if we should prevent variables with too many categories from being added to the control, or if we should just show a message that there are too many groups when changing to that control. Or we could possibly just pick the first N levels of the variable and show those groups ...

**Comment by jwildfire** [comment]
## Test Notes

Confirm that the chart doesn't draw when the user selects a group variable with more levels than `config.defaults.maxGroups` by changing the group by variable to AGE using the settings below in CAT. Also confirm that you can then change back to another variable and the chart renders as expected.   
```
{
    variables:{group:"ARM"},
    variableOptions:{
      group:["RACE","SEX","AGE"]
  },
};
 ```

**Comment by rchronowic** [comment]
Testing for this issue passed in CAT for both Firefox and Chrome. See below screen shot for Error message.

![image](https://user-images.githubusercontent.com/42471621/47572431-ee8d3f00-d908-11e8-9aa9-40916ae100bb.png)
