### ISSUE TITLE
Sync the group control when groupCols = false

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#136]
## Test Notes

Confirm that the group control defaults to "None" when `groupCols = false` and selects the option corresponding to `config.variables.group` otherwise.

**Comment by emmorris** [comment]
Confirmed that changing default settings in CAT to the snippet of code below did result in the "Group Variable" drop-down defaulting to "None" and without that it defaulted to "ARM" as expected.   "defaults": {
        "placeholderFlag": {
            "value_col": "AEBODSYS"
        },
        "maxPrevalence": 0,
        "maxGroups": 6,
        "totalCol": true,
        "prefTerms": false,
        "summarizeBy": "participant",
        "groupCols": false
    },
