### ISSUE TITLE
Refactor using modular code with ES6 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#17]
And then implement a build process using node/npm/rollup/babel similar to the one described in [webcharts-wrappers-boilerplate](https://github.com/RhoInc/webcharts-wrapper-boilerplate)

**Comment by jwildfire** [comment]
@samussiah Let's try to follow @nbryant's lead on modularization and use rollup + babel. Checkout the [package.json](https://github.com/RhoInc/ae-timelines/blob/master/package.json) and [scripts folder](https://github.com/RhoInc/ae-timelines/tree/master/scripts) for the safety explorer renderers as an example. The [boilerplate wiki](https://github.com/RhoInc/webcharts-wrapper-boilerplate/wiki) might provide some useful context as well.

**Comment by samussiah** [comment]
It's done.  It's modularized.  All recursive references and undeclared variables have been corrected.  <exhales tiredly>

**Comment by samussiah** [comment]
http://bl.ocks.org/samussiah/raw/90e524b9ef2fdf8214d491aaca4cd3b3/

**Comment by brittsikora** [comment]
@jwildfire - how do I test this?

**Comment by jwildfire** [comment]
@brittsikora I (or another dev) can do a code review on the pull request to test.

**Comment by brittsikora** [comment]
Should I assign this to you or perhaps Shane?

**Comment by jwildfire** [comment]
Lots more work done here. Should be close to done. See #29 for details.

**Comment by jwildfire** [comment]
Implemented in #29, so going to go ahead and close. Thanks again for all the good work, @samussiah!
