### ISSUE TITLE
Add Ability to Sort by Selected AEs

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#2]

**Comment by jwildfire** [comment]
Not sure what this one is going for. @brittsikora Any more details available?

**Comment by brittsikora** [comment]
I followed up with Jack:

"I think it might have been referring to the AE timelines, because we had a sponsor who just wanted to see timelines for the different insomnias (early, middle, late, etc.).  At present, you can sort by body system, but not by individual AE.  But really, I think that’s too much trouble; so we can ignore this for now."

**Comment by jwildfire** [comment]
OK - flagging this as low priority and clarifying the title. We may close later if it doesn't come up again.

**Comment by jwildfire** [comment]
Actually, just going to close, since this is actually in the wrong repo. We can create a new issue in https://github.com/RhoInc/ae-timelines if it comes up again.
