### ISSUE TITLE
Trouble Customizing Filters

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#20]
![aefeature](https://cloud.githubusercontent.com/assets/14914918/16530917/3ac485fc-3f98-11e6-91c0-d0bf79774dc5.PNG)

While customizing filters, I added a filter for sex and it flipped the colors and didn't give the new filter a header.

You also asked me to put "the code under the tech specs button" in here as well.

**Comment by brittsikora** [comment]
Here is the actual code:

//uses d3 v.3.5.17
//uses table.js from AE Explorer

var variables = {
  "id": "USUBJID",
  "major": "AEBODSYS",
  "minor": "AEDECOD",
  "filters": [
    "AEBODSYS",
    "AESEV",
    "TRT"
  ],
  "group": "SEX",
  "details": [
    "USUBJID",
    "SEX",
    "RACE",
    "TRT",
    "AEDECOD",
    "AESEV",
    "AESER",
    "AEOUT"
  ]
};

var settings = {
  "groups": [
    {
      "key": "M",
      "selected": true
    },
    {
      "key": "F",
      "selected": true
    },
    {
      "key": "",
      "selected": true
    }
  ],
  "defaults": {
    "maxPrevalence": "0.0",
    "prefTerms": "Hide",
    "diffCol": "Show"
  },
  "filterSettings": []
};

d3.csv(dataPath, function(error, csv) {
  aeExplorer.init(dataElement, data, variables, settings);
});
    

Best,
Amelia Bedelia

**Comment by jwildfire** [comment]
fixed in v2.0.1
