### ISSUE TITLE
Combine Settings and Variables object

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#21]
Biggest remaining hurdle is the settings.groups object, but that can be generated automatically. The chartfoundry renderer already does something [similar](https://github.com/RhoInc/chf-renderer-aeexplorer/blob/master/src/Renderer.js#L58-L59).

**Comment by samussiah** [comment]
Removed variables argument to table.init() with the assumption that the settings argument contains a 'variables' property.

**Comment by jwildfire** [comment]
Sounds good. Not seeing [the branch](https://github.com/RhoInc/aeexplorer/branches). Did you push it to github?

**Comment by samussiah** [comment]
Not yet.  I'm going to attempt to modularize the code before I push the branch.  Should have something up by the end of the day.

**Comment by jwildfire** [comment]
Sounds good. See my comment on #17 re: modularization.

**Comment by samussiah** [comment]
http://bl.ocks.org/samussiah/raw/90e524b9ef2fdf8214d491aaca4cd3b3/

**Comment by brittsikora** [comment]
@jwildfire - How I test dis?

**Comment by jwildfire** [comment]
:+1: 

I just confirmed by looking at the example above.

**Comment by brittsikora** [comment]
Awesome - closing now to stay consistent
