### ISSUE TITLE
Diff column displaying even when defaults.diffCol is set to 'Hide'.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/aeexplorer#26]

**Comment by brittsikora** [comment]
@jwildfire - How do I test this as well?

**Comment by jwildfire** [comment]
@brittsikora Update the gist (or create a new one) to confirm that changing the setting updates the chart appropriately. http://bl.ocks.org/samussiah/90e524b9ef2fdf8214d491aaca4cd3b3

@samussiah can walk you through that process once he gets back from :four_leaf_clover: land

**Comment by jwildfire** [comment]
Working as expected in #29.
