### ISSUE TITLE
Group columns not sorting alphabetically.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/aeexplorer#27]

**Comment by brittsikora** [comment]
Columns look logical to me, but I'm not sure what it looked like before. @jwildfire - is the column order presenting as expected?

**Comment by jwildfire** [comment]
Yeah, would've been good to have a bit more detail in this issue. IIRC, this had to do with the column headers getting out of sync with the values. @samussiah do we have a data set/chart where this was failing? Or can you point me to the updated lines or code that resolve the problem?

**Comment by jwildfire** [comment]
Actually, I think this was resolved in #12, so this may actually be a duplicate issue. @samussiah can you confirm?

**Comment by samussiah** [comment]
I should have said 'alpha-numerically' instead of 'logically'.  When the group values are not specified in the user-defined settings they'll be sorted.  See line 45-47 in [init.js](https://github.com/RhoInc/aeexplorer/blob/refactor/src/init.js).

**Comment by jwildfire** [comment]
@samussiah covered this in #29 [here](https://github.com/RhoInc/aeexplorer/blob/refactor/src/chart/init.js#L50-L52)
