### ISSUE TITLE
Default settings should be synced with custom settings.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/aeexplorer#31]

**Comment by jwildfire** [comment]
I did a *very* basic implementation [here](https://github.com/RhoInc/aeexplorer/blob/refactor/src/createChart.js#L12). Created #35 for future improvements

**Comment by jwildfire** [comment]
even the basic implementation isn't working for filters ☹️ . need to resolve for 3.0.0. re-opening.

**Comment by jwildfire** [comment]
Fixed in #41

**Comment by brittsikora** [comment]
@jwildfire How should I test this?
