### ISSUE TITLE
QC/document the raw data download functionality

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#36]
Let the user download the table data when `chart.config.validation == true`. An early version of the functionality is already present in `aetable.init()` and `\util`, but isn't documented or exposed to the user.

**Comment by jwildfire** [comment]
Note that the csv implementation is potentially buggy as written.

**Comment by samussiah** [comment]
https://github.com/RhoInc/aeexplorer/wiki/Configuration#settingsvalidation

**Comment by brittsikora** [comment]
Expected Outcome: Read through the documentation on the raw download functionality and confirm it looks okay

Result: Pass
