### ISSUE TITLE
Convert empty defaults from empty array to 'null'

### ISSUE THREAD

**Issue by bzkrouse** [RhoInc/aeexplorer#46]
Defaults in AE explorer are specified as [], while defaults in some other safety widgets are 'null'.  Convert all defaults to 'null' to make consistent and to make more sense logically.

**Comment by jwildfire** [comment]
Good catch, @bzkrouse. We'll cover this in the next release.

**Comment by jwildfire** [comment]
Changing defaults for the following settings from `[]` to `null` and updating `setDefaults.js` accordingly:

- config.variables.details
- config.filters[].start
- config.variableOptions
- config.groups

**Comment by jwildfire** [comment]
# Test Notes

Technical change - No UI differences, so no feature testing needed. Existing regression tests are sufficient.
