### ISSUE TITLE
Automatically enter search criteria

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#49]
For the search bar and incidence threshold, the user must currently click away from the entered value or hit the enter button for the function to filter on the entered value. We should try to automate this so the user doesn't think the function is broken.

**Comment by jwildfire** [comment]
## Test Notes

Confirm that the graphics updates after each keystroke in the search and filter by prevalence inputs (instead of after focus leaves the input altogether)

**Comment by danedexF5** [comment]
@jwildfire I think this is working as expected. Reason I say "think" is that Filter by Prevalence grays out once I start typing in search. If that is the desired outcome, then pass.

**Comment by jwildfire** [comment]
@danedexF5 Yeah, that is the correct behavior. As long as both of the inputs are updating as described independently, we're good.
