### ISSUE TITLE
Add Filters for Details View

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#5]
Be able to filter (e.g. sex, severity, etc.) in details view

**Comment by jwildfire** [comment]
We could add https://datatables.net/, but it might be better to add a filter on the main page instead, and leave the details table as a simple listing. Of course, adding a filter on the primary view that requires different logic for "participant-level" filters (as opposed to the current "event-level" filters), which is complex.

**Comment by jwildfire** [comment]
Patient level filters are implemented on the main page. We need to decide on the proper behavior for the details table in 3.0.0. 

For now, we should probably just have the details table render with the same filtered data being used in the main table, and add some text to the label indicating which filters are active ("XXX records shown for System Organ Class=X and Gender=Y"). 

We could consider leaving the controls active in the detail table view, but that is certainly a bit more work, so I'd prefer to leave that for a future release.

**Comment by jwildfire** [comment]
Initial commit in branch `detail filters` works well for participant filters, but not event filters. Need to figure out the best way update.  

<img width="935" alt="screen shot 2017-01-14 at 8 55 41 am" src="https://cloud.githubusercontent.com/assets/3680095/21956499/4bb0e894-da37-11e6-94d6-1f14ba3a9d3e.png">
