### ISSUE TITLE
Fix the "too many groups error text"

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#50]
The text that shows up with the max groups error seems to be hardcoded and is currently incorrect: minor fix

**Comment by jwildfire** [comment]
@brittsikora This appears to be acting reasonably. Going to close unless you can add more detail about the bug. 

<img width="1428" alt="screen shot 2017-03-21 at 8 32 28 am" src="https://cloud.githubusercontent.com/assets/3680095/24155426/078a5516-0e11-11e7-87ba-1bff058212eb.png">

**Comment by jwildfire** [comment]
Ooooooh - I see it now current and max values are transposed. Will fix. 😳

**Comment by jwildfire** [comment]
Actually there was just a stray '6' in the error message. Fixing!
