### ISSUE TITLE
Reformat the `config.groups` setting

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#58]
Specifying a list of group levels to be displayed (`["Placebo","Treatment A"]`) throws an error as shown. 
<img width="924" alt="screen shot 2017-03-29 at 12 46 17 pm" src="https://cloud.githubusercontent.com/assets/3680095/24473388/ec97f4e8-147d-11e7-8a65-f31edb85af55.png">

Hopefully this is just buggy error checking and the functionality actually works ok.

**Comment by jwildfire** [comment]
This actually works, but wiki documentation was wrong. `settings.groups` should be an array of objects (e.g. `[{key:"Placebo"},{"key":"Treatment A"}]` not an array of character (`["Placebo","All"]`). The [wiki has been updated](https://github.com/RhoInc/aeexplorer/wiki/Configuration#settingsgroups).


This behaviour is pretty silly though, so tweaking this issue to update to support the more logical and convenient array of character format.

**Comment by jwildfire** [comment]
Test Notes: confirm that all of the following setting render the specified groups: 
- `{"groups":["Placebo"]}`
- `{"groups":[{"key":"Placebo"}]}`
- `{"groups":[{"key":"Placebo"},"Treatment A"]}`
- `{"groups":[{"key":"NotAGroup"},"Treatment A"]} //only renders treatment a column`
- `{"groups":["NotAGroup"]} //renders all groups (since no valid groups are specified`

**Comment by brittsikora** [comment]
Pass

{"groups":["Placebo"]}
![58a](https://user-images.githubusercontent.com/14914918/28338158-0ac18b78-6bd6-11e7-9a06-3cf1dee03abb.JPG)

{"groups":[{"key":"Placebo"}]}
![image](https://user-images.githubusercontent.com/14914918/28338180-1c6e852e-6bd6-11e7-8b54-3c66f7fedb03.png)

{"groups":[{"key":"Placebo"},"Treatment A"]}
![58c](https://user-images.githubusercontent.com/14914918/28338196-2dce4aa2-6bd6-11e7-9490-b32e2c758333.JPG)

{"groups":[{"key":"NotAGroup"},"Treatment A"]} 
![58d](https://user-images.githubusercontent.com/14914918/28338212-3de610aa-6bd6-11e7-8299-106b26da16aa.JPG)

{"groups":["NotAGroup"]} 
![58e](https://user-images.githubusercontent.com/14914918/28338236-50cc4c16-6bd6-11e7-9d93-e8a206e3165d.JPG)
