### ISSUE TITLE
`settings.plot_settings.margin` should affect rate chart...

### ISSUE THREAD

**Issue by samussiah** [RhoInc/aeexplorer#62]
...like `settings.plot_settings.diffMargin` affects difference chart.

**Comment by jwildfire** [comment]
# Test Notes

Confirm in CAT that margins are drawn for the dot plot when `plotSettings.margin` is specified. Just tweak the following settings object, and confirm that the margin changes as expected: `{plotSettings: {margin: {left: 40, right: 40}}}`
