### ISSUE TITLE
sas: Add setting for default display type (Participant vs. Event)

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#63]

**Comment by jwildfire** [comment]
Will simplify validation testing - let's use `defaults.summarizeBy` with valid options: 
- "participant" (default)
- "event"

**Comment by samussiah** [comment]
pretty straightforward, just added the new config setting

**Comment by brittsikora** [comment]
Expected Outcome: Use the following settings to summarize by participant or event on default
Event: {"validation": true
,"defaults":
{"summarizeBy": "event"}
}
Participant: {"validation": true
,"defaults":
{"summarizeBy": "participant"}
}

Result:
