### ISSUE TITLE
Update download attribute of .csv link to a named value.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/aeexplorer#65]
Per @srosanba , the file is simply named 'true' without an extension.  Perhaps name it '[dataset name]-[group variable name] Summary' to give it a useful context.

**Comment by jwildfire** [comment]
My recollection is that this is a very browser-specific issue. Will look in to it a bit more ...

**Comment by samussiah** [comment]
File download just doesn't work in IE, but you can name the file in both Chrome and FireFox.

**Comment by samussiah** [comment]
Download works and is named in all three browsers as described [here](https://github.com/RhoInc/aeexplorer/wiki/Configuration#settingsvalidation)

**Comment by brittsikora** [comment]
Expected Outcome: Downloading a file will save it as major term-minor term-participant or event

Result:
