### ISSUE TITLE
Allow default filter values to be applied on initial load

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#66]
Just add a `default` array to the `settings.variables.filters[]` objects, like this?

```
    "filters":[
      {
        "value_col": "AESER",
        "label": "Serious?",
        "type":"event",
        "default":["Y"]
      },
      {
        "value_col": "SEX",
        "label": "Sex",
        "type":"participant",
        "default":["M"]
      }
    ]
  }
```

**Comment by brittsikora** [comment]
Expected Outcome: Enter the following settings to default the filters on initial load

{"validation": true
,"variables":
{"filters":
[
{"value_col": "AESER"
,"label": "Srs?"
,"type": "event"
,"start": ["Y"]}
]
}
}

Result:
