### ISSUE TITLE
sas: CSV for validation not doubling up double quotes

### ISSUE THREAD

**Issue by srosanba** [RhoInc/aeexplorer#67]
When a minorCategory value has double quotes within it, the CSV should double those double quotes. 
For instance:
"Decrease in heart's ability to pump blood during the "active" phas of the heartbeat (systole)"
Should actually appear as:
"Decrease in heart's ability to pump blood during the ""active"" phas of the heartbeat (systole)"

**Comment by samussiah** [comment]
converting everything to character, replacing single double quotes with double double quotes, then quoting the whole field

**Comment by brittsikora** [comment]
@jroden to test
