### ISSUE TITLE
sas: CSV is the same for both participant and event summaries

### ISSUE THREAD

**Issue by srosanba** [RhoInc/aeexplorer#68]
The same CSV file results from test1.json and test2.json. Both CSV files seem to correspond to the participant setting (i.e., test1.json).

**Comment by samussiah** [comment]
Just redefining download link every time the chart re-initializes.

**Comment by brittsikora** [comment]
Expected Result: Summarizing by participant will yield a download citing "participant" in the title and summarizing by event will yield a download citing "event" in the title

Result: Pass

![68](https://user-images.githubusercontent.com/14914918/27934109-438e70fa-6272-11e7-973c-a5ca615ee7cd.JPG)

![68b](https://user-images.githubusercontent.com/14914918/27934110-44a71d66-6272-11e7-9baf-822c56b63036.JPG)
