### ISSUE TITLE
sas: Applying filters does not impact CSV download file

### ISSUE THREAD

**Issue by srosanba** [RhoInc/aeexplorer#69]
For test9.json we are supposed to subset on serious events for males. This subsetting reduces the denominators to 30, 29, 26 in the browser. However, the CSV download still shows 50, 50, 50.

**Comment by samussiah** [comment]
Just redefining download link every time the chart re-initializes.

**Comment by brittsikora** [comment]
Expected Outcome: Enter {"validation": true} + filter and csv should show filtered data

Result:

**Comment by brittsikora** [comment]
In my comment above, I thought that the intended use was to download the data from a minor category after expanding the larger bodysys. That functionality does not work, but filtering and downloading the filtered data does work, so this is a pass. 

![69](https://user-images.githubusercontent.com/14914918/27934491-fd21b59e-6273-11e7-85ef-db4414f70a66.JPG)
