### ISSUE TITLE
Refactor in-browser csv generation

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#70]
See [here](https://stackoverflow.com/questions/14964035/how-to-export-javascript-array-info-to-csv-on-client-side) (and maybe also [here](https://stackoverflow.com/questions/18848860/javascript-array-to-csv/18849208)) for an improved implementation of our csv export process.

**Comment by samussiah** [comment]
Refactored and compatible with IE in #72 .

**Comment by brittsikora** [comment]
Expected Outcome: Entering {"validation": true} will show the download CSV option. CSV can be saved and viewed.

Result:
