### ISSUE TITLE
Make Treatment Group Columns Optional

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#76]
Request from Kristen on 7/12:

"a.	Remove A/B columns from ‘AE Table’. Also remove TRT column from the listings produced when you click on the category column"

Need this by the 26th

**Comment by jwildfire** [comment]
Test Notes: confirm that the following settings work as expected: 
- `{"defaults":{"totalCol":true,"groupCols":true}}`
- `{"defaults":{"totalCol":true,"groupCols":false}}`
- `{"defaults":{"totalCol":false,"groupCols":true}}`
- `{"defaults":{"totalCol":false,"groupCols":false}} //No chart rendered. should throw an informative error. `

**Comment by brittsikora** [comment]
Pass

{"defaults":{"totalCol":true,"groupCols":true}}
![76a](https://user-images.githubusercontent.com/14914918/28338034-939191ec-6bd5-11e7-9d7f-a7f968a0b3ac.JPG)

{"defaults":{"totalCol":true,"groupCols":false}}
![76b](https://user-images.githubusercontent.com/14914918/28338053-a955910e-6bd5-11e7-8fac-483789033e60.JPG)

{"defaults":{"totalCol":false,"groupCols":true}}
![76c](https://user-images.githubusercontent.com/14914918/28338072-bab0f93e-6bd5-11e7-943a-aed0ff2cb3ad.JPG)

{"defaults":{"totalCol":false,"groupCols":false}}
![76d](https://user-images.githubusercontent.com/14914918/28338103-d6f12272-6bd5-11e7-863e-2582e4edeb7f.JPG)
