### ISSUE TITLE
Add Sort/Filter Option on Listing

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#77]
Request from Kristen on 7/12:

"3.	Add sort/filter options to the listing produced from the ‘AE Table’ when you click on the category column."

**Comment by brittsikora** [comment]
I'd like to discuss feasibility and priority on this request

**Comment by emmorris** [comment]
Sorting and searching makes the most sense - will include with next major release using Webcharts

**Comment by matthiazzz** [comment]
Is there any timeline available when this switch to Webcharts will be done?

**Comment by jwildfire** [comment]
@matthiazzz There's currently no timeline for doing a full refactor using webcharts and releasing v4.0. 

However, if you are just looking for enhanced table functionality with search/sort/pagination, it would be pretty easy to just switch the detail table over to a webcharts table object in the minor release which is scheduled for the next month or so. Just let us know if that would be helpful and we'll see what we can do. 

(cc: @emmorris & @samussiah)

**Comment by jwildfire** [comment]
Implemented in v3.3 via the new`config.defaults.webchartsDetailsTable` option. Just set the option to `true` and make sure to include `webcharts.js` and `webcharts.css`.

**Comment by jwildfire** [comment]
## Test Notes

Test in CAT with the following settings: `{ defaults:{webchartsDetailTable:true}}` Confirm that the detail table view (accessed by clicking the label of any row in the summary table), is rendered using a webcharts table, and that sort, search, pagination and export work as expected.

**Comment by danedexF5** [comment]
Webcharts Table display appears when using detail view. Confirmed.
