### ISSUE TITLE
Entering a value doesn't work in IE

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/aeexplorer#78]
Entering a prevalence threshold or search term doesn't work when you hit enter

**Comment by jwildfire** [comment]
Is there a workaround for this? Or there is currently no way to use these inputs in IE?

**Comment by brittsikora** [comment]
You can enter a value and try to click on a category or something that works and it updates

**Comment by jwildfire** [comment]
OK - calling it low priority then. Debating whether to fix it in 3.1 or not. @samussiah do you think there is an obvious/quick fix for this?

**Comment by samussiah** [comment]
Disabling "enable protected mode" in IE fixes this issue: https://answers.microsoft.com/en-us/ie/forum/ie11-iewindows8_1/unable-to-type-in-internet-explore-11/7b6c26de-8b51-43c2-90d8-788e8791ffa3

**Comment by brittsikora** [comment]
Still isn't working for me after that fix, but the tooltips do work now?

**Comment by brittsikora** [comment]
Fix doesn't work, but users can still search if they enter a value and remove focus from the search box by clicking outside of it or by pressing tab
