### ISSUE TITLE
Add JSON schema for settings object

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#80]

**Comment by jwildfire** [comment]
Test Notes: Confirm that the automatic form for the renderer appears in CAT. No code changes, so no formal testing with AE explorer needed.

**Comment by brittsikora** [comment]
Pass

![80](https://user-images.githubusercontent.com/14914918/28337265-17814f22-6bd3-11e7-93bc-378b557fb42d.JPG)
