### ISSUE TITLE
Automatically hide the difference column if less than 2 groups are renderered

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#82]

**Comment by jwildfire** [comment]
The code at aeTable.init:144 is including the total columm in the nGroups count. Fixing that should fix this. 

```
  if (nGroups > 1 && chart.config.defaults.diffCol) {
        header1.append('th').text('Difference Between Groups').attr('class', 'diffplot');
        header2.append('th').attr('class', 'diffplot axis');
    }
```

**Comment by jwildfire** [comment]
Fixed the code above, and set `settings.defaults.diffCol` to false when `setting.defaults.groupCols` is false

**Comment by jwildfire** [comment]
Test Notes: Confirm that difference diamonds column is hidden with settings: `{"groups":["Placebo"]}` and `{"defaults":{"groupCols":false}}`, but not with `{"groups":["Placebo","Treatment A"]}`

**Comment by brittsikora** [comment]
Pass

![82a](https://user-images.githubusercontent.com/14914918/28337978-5d74cb7e-6bd5-11e7-9549-053a88e331e7.JPG)

![82b](https://user-images.githubusercontent.com/14914918/28337980-5f1848c0-6bd5-11e7-8c47-49278de6daa0.JPG)

![82c](https://user-images.githubusercontent.com/14914918/28337983-6087d91e-6bd5-11e7-96e0-176ad5f7fea8.JPG)
