### ISSUE TITLE
Hide the total column if only one group is renderered

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#83]
Rendering the total column is a bit confusing, since it is identical to (and thus overwrites) the group point in this case.

**Comment by jwildfire** [comment]
Test Notes: Confirm that total column is automatically hidden with settings: `{"groups":["Placebo"]}`, but not with `{"groups":["Placebo","Treatment A"]}`

**Comment by brittsikora** [comment]
Pass

![83a](https://user-images.githubusercontent.com/14914918/28337212-e3691fbc-6bd2-11e7-8168-94c6a5c1a740.JPG)

![83b](https://user-images.githubusercontent.com/14914918/28337216-e4e3aae2-6bd2-11e7-8756-22775fc7fbe1.JPG)
