### ISSUE TITLE
Update Error message for sparse data

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#96]
Currently, the error message below is thrown if there are no AEs that match the current filters -
 even if there *are* participants that match the filters. It might be better to throw a different error message in the case where there are participants (but none of them have AEs). 

OR maybe we should draw a table with 0% throughout ... 

<img width="552" alt="screen shot 2017-10-23 at 5 50 17 pm" src="https://user-images.githubusercontent.com/3680095/31919952-b9174a4c-b81a-11e7-9e77-20ca6acd0038.png">

**Comment by jwildfire** [comment]
Test Notes: Confirm that error message now says "No AEs" are found instead of "No Data" is found

**Comment by danedexF5** [comment]
Confirmed, now says No AEs
