### ISSUE TITLE
Prevalence filter not working as expected ... 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#99]
Last row shouldn't be visible. See project 273. 
<img width="805" alt="screen shot 2017-11-06 at 8 31 34 am" src="https://user-images.githubusercontent.com/3680095/32457276-67ed82b2-c2dd-11e7-8ae8-5e2a2a7bfa89.png">

**Comment by jwildfire** [comment]
Pretty sure the problem occurs when `group` is set, but `groupCols` is marked false. Filtering is still occurring based on the maximum rate in the group columns (even though those columns are hidden).

**Comment by jwildfire** [comment]
Test Notes: 
- In previous versions, setting the prevelance filter to 10, would display rows with values less than 10 when groupCols was false. 
- Confirm that the prevalence filter works as expected with the following settings: 

`{"variables":{"id":"USUBJID","major":"AEBODSYS","minor":"AEDECOD","group":"ARM"},"defaults":{"groupCols":false}}`

**Comment by dschwentker** [comment]
Tested and passed in all browsers.
